name: Build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build with xcaddy
        run: xcaddy build --with github.com/WingLim/caddy-webhook=./