name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger event on caddy-docker
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: WingLim/caddy-docker
          event-type: release-tagged
          client-payload: '{"tag": "${{ github.event.release.tag_name }}"}'
